### ISSUE TITLE
Error on installation: web_menu_hide_8

### ISSUE THREAD

**Issue by akram1** [OpenSur/Odoo_addons#26]
Odoo8 build 14/3/2015 Linux 64
Installation stops when updating Module Llist:
Traceback (most recent call last):
  File "/media/akram/Data/projects/servers/Odoo8/source/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/media/akram/Data/projects/servers/Odoo8/source/openerp/http.py", line 567, in dispatch
    result = self._call_function(*_self.params)
  File "/media/akram/Data/projects/servers/Odoo8/source/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/media/akram/Data/projects/servers/Odoo8/source/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/media/akram/Data/projects/servers/Odoo8/source/openerp/http.py", line 300, in checked_call
    return self.endpoint(_a, *_kw)
  File "/media/akram/Data/projects/servers/Odoo8/source/openerp/http.py", line 796, in __call__
    return self.method(_args, *_kw)
  File "/media/akram/Data/projects/servers/Odoo8/source/openerp/http.py", line 396, in response_wrap
    response = f(_args, *_kw)
  File "/media/akram/Data/projects/servers/Odoo8/source/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/media/akram/Data/projects/servers/Odoo8/source/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/media/akram/Data/projects/servers/Odoo8/source/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/media/akram/Data/projects/servers/Odoo8/source/openerp/api.py", line 393, in old_api
    result = new_api(recs, _args, *_kwargs)
  File "/media/akram/Data/projects/servers/Odoo8/source/openerp/api.py", line 397, in new_api
    result = [method(rec, _args, *_kwargs) for rec in self]
  File "/media/akram/Data/projects/servers/Odoo8/source/openerp/addons/base/module/wizard/base_module_update.py", line 15, in update_module
    self.updated, self.added = self.env['ir.module.module'].update_list()
  File "/media/akram/Data/projects/servers/Odoo8/source/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/media/akram/Data/projects/servers/Odoo8/source/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/media/akram/Data/projects/servers/Odoo8/source/openerp/addons/base/module/module.py", line 654, in update_list
    handler.load_addons()
  File "/media/akram/Data/projects/servers/Odoo8/source/openerp/http.py", line 1298, in load_addons
    m = __import__('openerp.addons.' + module)
  File "/media/akram/Data/projects/servers/Odoo8/source/openerp/modules/module.py", line 79, in load_module
    f, path, descr = imp.find_module(module_part, ad_paths)
ImportError: No module named web_menu_hide_8

**Comment by OpenSur** [comment]
Please rename addon directory to web_menu_hide.... Will change it in repository as soon as possible

**Comment by OpenSur** [comment]
Corrected, let me know...

**Comment by akram1** [comment]
Hide menu works now
