### ISSUE TITLE
Website_search,UnicodeEncodeError: 'ascii' codec can't encode characters in...

### ISSUE THREAD

**Issue by AlexProc13** [OpenSur/Odoo_addons#36]
Hello from Russia. Module - Website Search. Normal is set but not working correctly. Normal looking for English words. But when I ask the Russian word search - an error "500: Internal Server Error»

Traceback

Traceback (most recent call last):
  File "/opt/odoo/addons/website/models/ir_http.py", line 196, in _handle_exception
    response = super(ir_http, self)._handle_exception(exception)
  File "/opt/odoo/openerp/addons/base/ir/ir_http.py", line 146, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 659, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/addons/base/ir/ir_http.py", line 172, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/openerp/http.py", line 677, in dispatch
    r = self._call_function(*_self.params)
  File "/opt/odoo/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/openerp/http.py", line 300, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/openerp/http.py", line 796, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/openerp/http.py", line 396, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/addons/website_search/controllers/main.py", line 559, in search_results
    index=search_html.find(str(search_term), 0)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)

Help)))

**Comment by AlexProc13** [comment]
odoo v 8
