### ISSUE TITLE
website_search error on installing - Odoo 8 (31/1/2015)

### ISSUE THREAD

**Issue by akram1** [OpenSur/Odoo_addons#4]
Odoo Server Error
Traceback (most recent call last):
  File "/media/akram/Data/projects/servers/odoo8/source/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/media/akram/Data/projects/servers/odoo8/source/openerp/http.py", line 567, in dispatch
    result = self._call_function(*_self.params)
  File "/media/akram/Data/projects/servers/odoo8/source/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/media/akram/Data/projects/servers/odoo8/source/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/media/akram/Data/projects/servers/odoo8/source/openerp/http.py", line 300, in checked_call
    return self.endpoint(_a, *_kw)
  File "/media/akram/Data/projects/servers/odoo8/source/openerp/http.py", line 796, in __call__
    return self.method(_args, *_kw)
  File "/media/akram/Data/projects/servers/odoo8/source/openerp/http.py", line 396, in response_wrap
    response = f(_args, *_kw)
  File "/media/akram/Data/projects/servers/odoo8/source/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/media/akram/Data/projects/servers/odoo8/source/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/media/akram/Data/projects/servers/odoo8/source/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/media/akram/Data/projects/servers/odoo8/source/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/media/akram/Data/projects/servers/odoo8/source/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/media/akram/Data/projects/servers/odoo8/source/openerp/addons/base/module/module.py", line 498, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/media/akram/Data/projects/servers/odoo8/source/openerp/modules/registry.py", line 366, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/media/akram/Data/projects/servers/odoo8/source/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/media/akram/Data/projects/servers/odoo8/source/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/media/akram/Data/projects/servers/odoo8/source/openerp/modules/loading.py", line 176, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/media/akram/Data/projects/servers/odoo8/source/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/media/akram/Data/projects/servers/odoo8/source/openerp/tools/convert.py", line 901, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/media/akram/Data/projects/servers/odoo8/source/openerp/tools/convert.py", line 974, in convert_xml_import
    doc = etree.parse(xmlfile)
  File "lxml.etree.pyx", line 2942, in lxml.etree.parse (src/lxml/lxml.etree.c:54187)
  File "parser.pxi", line 1550, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:79703)
  File "parser.pxi", line 1580, in lxml.etree._parseFilelikeDocument (src/lxml/lxml.etree.c:80012)
  File "parser.pxi", line 1463, in lxml.etree._parseDocFromFilelike (src/lxml/lxml.etree.c:78908)
  File "parser.pxi", line 1019, in lxml.etree._BaseParser._parseDocFromFilelike (src/lxml/lxml.etree.c:75905)
  File "parser.pxi", line 564, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:71739)
  File "parser.pxi", line 645, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:72614)
  File "parser.pxi", line 585, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:71955)
XMLSyntaxError: Opening and ending tag mismatch: div line 195 and template, line 228, column 12

**Comment by akram1** [comment]
website search version is 2/2/2015

**Comment by OpenSur** [comment]
Fixed. Please download and retry install...
