### ISSUE TITLE
website_lang_flag error on adding a new language - Odoo 8 (31/1/2015)

### ISSUE THREAD

**Issue by akram1** [OpenSur/Odoo_addons#5]
I added a flag (6Kb gif) to English language but no flag in the web site so I tried to add another one and got this error:
Odoo Server Error
Traceback (most recent call last):
  File "/media/akram/Data/projects/servers/odoo8/source/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/media/akram/Data/projects/servers/odoo8/source/openerp/http.py", line 567, in dispatch
    result = self._call_function(*_self.params)
  File "/media/akram/Data/projects/servers/odoo8/source/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/media/akram/Data/projects/servers/odoo8/source/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/media/akram/Data/projects/servers/odoo8/source/openerp/http.py", line 300, in checked_call
    return self.endpoint(_a, *_kw)
  File "/media/akram/Data/projects/servers/odoo8/source/openerp/http.py", line 796, in __call__
    return self.method(_args, *_kw)
  File "/media/akram/Data/projects/servers/odoo8/source/openerp/http.py", line 396, in response_wrap
    response = f(_args, *_kw)
  File "/media/akram/Data/projects/servers/odoo8/source/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/media/akram/Data/projects/servers/odoo8/source/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/media/akram/Data/projects/servers/odoo8/source/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/media/akram/Data/projects/servers/odoo8/source/addons/website/models/website.py", line 828, in lang_install
    self.pool['website'].write(cr, uid, website_ids, data)
  File "/media/akram/Data/projects/servers/odoo8/source/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/media/akram/Data/projects/servers/odoo8/source/addons/website/models/website.py", line 182, in write
    self._get_languages.clear_cache(self)
AttributeError: 'function' object has no attribute 'clear_cache'

**Comment by akram1** [comment]
website lang flag version is 2/2/2015

**Comment by OpenSur** [comment]
Fixed error on 'clear_cache'. Please download and retry.

**Comment by akram1** [comment]
I tired the fix but the problem sill exists exactly the same.

**Comment by OpenSur** [comment]
Did you stopped and restarted odoo server? It needs to recompile website.py...

**Comment by akram1** [comment]
I upgraded to latest version (9/2'2015) and restarted the server but it is sill the same no flag on navbar

**Comment by OpenSur** [comment]
Can you help me to reproduce your situation?. Do you have more than one language enabled in your website?

**Comment by akram1** [comment]
I found the solution to no flag shown by replacing line 12 in website_lang_flags.xml:
t t-if="request.context.get('lang') == lg[0]"
